version: "3.1"

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: ./
      dockerfile: build/Dockerfile
    volumes:
      - .:/migrations
    command: ["-database", "postgres://root:secret@db:5432/mydbname?sslmode=disable", "-path", "/migration", "up"]
    links: 
        - db
    
volumes:
  postgres_data: